PeakKino/PeakKino/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('videos/', include(("videos.urls", 'videos'), namespace='videos')),
    path('accounts/', include(("accounts.urls", 'accounts'), namespace='accounts')),
    path('', home_view, name='home')
]

PeakKino/accounts/urls.py
from django.urls import path
from .views import CustomLoginView, logout_view, register, approve_accounts, approve_account

app_name="accounts"
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register, name='register'),
    path('approve_accounts/', approve_accounts, name='approve_accounts'),
    path('approve_account/<int:id>/', approve_account, name='approve_account'),
]

PeakKino/videos/urls.py
from django.urls import path
from .views import watch_video, upload_clip, video_details, all_videos, content_18_plus, delete_clip, upload_movie, delete_movie, all_movies, all_clips, create_show, search, update_timestamp, upload_subtitle, delete_subtitle, all_shows, show_details, create_season, upload_episode, delete_episode, delete_season, delete_show

app_name="videos"
urlpatterns = [
    path('<int:video_id>/', video_details, name='video_details'),
    path('<int:video_id>/watch/', watch_video, name="watch_video"),
    path('allvideos/', all_videos, name="all_videos"),
    path('allmovies/', all_movies, name="all_movies"),
    path('allclips/', all_clips, name="all_clips"),
    path('18plus/', content_18_plus, name="18_plus"),
    path('upload/clip/', upload_clip, name='upload_clip'),
    path('delete/clip/<int:clip_id>/', delete_clip, name="delete_clip"),
    path('upload/movie/', upload_movie, name='upload_movie'),
    path('delete/movie/<int:movie_id>/', delete_movie, name="delete_movie"),
    path('upload/show/', create_show, name="create_show"),
    path('search/', search, name="search"),
    path('<int:video_id>/updatetimestamp/', update_timestamp, name="update_timestamp"),
    path('upload/subtitle/<int:video_id>/', upload_subtitle, name="upload_subtitle"),
    path('delete/subtitle/<int:subtitle_id>/', delete_subtitle, name="delete_subtitle"),
    path('allshows/', all_shows, name="all_shows"),
    path('shows/<int:show_id>/', show_details, name="show_details"),
    path('upload/season/<int:show_id>/', create_season, name="create_season"),
    path('upload/episode/<int:season_id>/', upload_episode, name="upload_episode"),
    path('delete/episode/<int:episode_id>/', delete_episode, name="delete_episode"),
    path('delete/season/<int:season_id>/', delete_season, name="delete_season"),
    path('delete/show/<int:show_id>/', delete_show, name="delete_show"),
]

PeakKino/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}" >
    <title>PeakKino</title>
    
</head>
<body>
    <div class="template-content">
        <nav class="navigation">
            <ul class="links-nav">
                <li>
                    <a href="/">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'videos:all_videos' %}">All videos</a>
                    </li>
                    <li>
                        <a href="{% url 'videos:all_movies' %}">Movies</a>
                    </li>
                    <li>
                        <a href="{% url 'videos:all_shows' %}">Shows</a>
                    </li>
                    <li>
                        <a href="{% url 'videos:all_clips' %}">Clips</a>
                    </li>
                    {% if request.user.age >= 18 %}
                        <li>
                            <a href="{% url 'videos:18_plus' %}">18+ content</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
                <div class="search-container">
                    {% if query == None %}
                        <input type="text" id="search-input" placeholder="Search"/>
                    {% else %}
                        <input type="text" id="search-input" placeholder="{{query}}"/>
                    {% endif %}
                    <form id="search-form">
                        <select id="type-select" name="type">
                            <option value="all" selected>All</option>
                            <option value="movies">Movies</option>
                            <option value="clips">Clips</option>
                            <option value="shows">Shows</option>
                        </select>
                    </form>
                    <button id="search-button">Search</button>
                </div>
            {% endif %}

            <ul class="accounts-nav">
                {% if request.user.is_authenticated %}
                <li>
                    {{ request.user.user_name }}
                </li>
                {% if request.user.is_superuser %}
                    <li>
                        <a href="{% url 'accounts:approve_accounts' %}">Approve accounts</a>
                    </li>
                {% endif %}
                <li>
                    <a href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                {% else %}
                    <li>
                        <a href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var defaultType = "all";

        var typeSelect = document.getElementById('type-select');
        typeSelect.value = defaultType;

        document.getElementById('search-button').addEventListener('click', function() {
            var query = document.getElementById('search-input').value;
            var type = typeSelect.value;
            var url = '/videos/search/?query=' + encodeURIComponent(query) + '&type=' + type;
            console.log(url);
            window.location.href = url;
        });
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const clickableDivs = document.querySelectorAll(".clickable-div");
        
        clickableDivs.forEach(div => {
            div.addEventListener("mouseup", function(event) {
                const url = this.getAttribute("data-url");
                
                if (event.button === 0) {
                    window.location.href = url;
                }
                if (event.button === 1) {
                    window.open(url, '_blank');
                }
            });
        });
    });
</script>

{% block extra_scripts %}
{% endblock %}
</html>

PeakKino/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<h1>Jump back: </h1>
    {% for video, thumbnail_path, attached_obj, details_page_url in videos %}
            <h2>{{ attached_obj.title }}</h2>
            <img src="{{ thumbnail_path }}" style="max-width: 50%; max-height: 300px"/>
            <br/>
            {% if video.type == 'movie' %}
                <p>Type: movie</p>
                <p>Director: {{ attached_obj.director }}</p>
                <p>Lead actor: {{ attached_obj.lead_actor }}</p>
            {% endif %}
            <a href="{{ details_page_url }}">WATCH</a>
    {% endfor %}
{% endif %}
{% endblock %}