PeakKino/PeakKino/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('videos/', include(("videos.urls", 'videos'), namespace='videos')),
    path('accounts/', include(("accounts.urls", 'accounts'), namespace='accounts')),
    path('', home_view, name='home')
]

PeakKino/videos/urls.py
from django.urls import path
from .views import watch_video, upload_clip, video_details, all_videos, content_18_plus, delete_clip, upload_movie, delete_movie, all_movies, all_clips, create_show, search, update_timestamp, upload_subtitle, delete_subtitle, all_shows, show_details, create_season, upload_episode, delete_episode, delete_season, delete_show

app_name="videos"
urlpatterns = [
    path('<int:video_id>/', video_details, name='video_details'),
    path('<int:video_id>/watch/', watch_video, name="watch_video"),
    path('allvideos/', all_videos, name="all_videos"),
    path('allmovies/', all_movies, name="all_movies"),
    path('allclips/', all_clips, name="all_clips"),
    path('18plus/', content_18_plus, name="18_plus"),
    path('upload/clip/', upload_clip, name='upload_clip'),
    path('delete/clip/<int:clip_id>/', delete_clip, name="delete_clip"),
    path('upload/movie/', upload_movie, name='upload_movie'),
    path('delete/movie/<int:movie_id>/', delete_movie, name="delete_movie"),
    path('upload/show/', create_show, name="create_show"),
    path('search/', search, name="search"),
    path('<int:video_id>/updatetimestamp/', update_timestamp, name="update_timestamp"),
    path('upload/subtitle/<int:video_id>/', upload_subtitle, name="upload_subtitle"),
    path('delete/subtitle/<int:subtitle_id>/', delete_subtitle, name="delete_subtitle"),
    path('allshows/', all_shows, name="all_shows"),
    path('shows/<int:show_id>/', show_details, name="show_details"),
    path('upload/season/<int:show_id>/', create_season, name="create_season"),
    path('upload/episode/<int:season_id>/', upload_episode, name="upload_episode"),
    path('delete/episode/<int:episode_id>/', delete_episode, name="delete_episode"),
    path('delete/season/<int:season_id>/', delete_season, name="delete_season"),
    path('delete/show/<int:show_id>/', delete_show, name="delete_show"),
]

PeakKino/videos/models.py
from django.db import models
import uuid
import os
from datetime import datetime
from django.conf import settings

'''
    Fixes the circular import
    I.E. importing resource from video.models
    but then importing user from accounts.models
'''
def get_user_model():
    from accounts.models import User
    return User

class Resource(models.Model):
    AGE_RATING_CHOICES = [
        ('18', '18+'),
        ('15', '15+'),
        ('12', '12+'),
        ('7', '7+'),
        ('unrated', 'Unrated')
    ]
    age_rating = models.CharField(max_length=8, choices=AGE_RATING_CHOICES)

class Video(models.Model):
    TYPE_CHOICES = [
        ('movie', 'Movie'),
        ('episode', 'Episode'),
        ('clip', 'Clip'),
        ('other', 'Other')
    ]
    uploaded = models.DateTimeField()
    uuid = models.CharField(max_length=36, default=uuid.uuid4, editable=False, unique=True)
    extension = models.CharField(max_length=8, default='mp4')
    type = models.CharField(max_length=10, choices=TYPE_CHOICES)

    def save(self, *args, **kwargs):
        if self.pk is None: 
            self.uuid = uuid.uuid4()
            self.uploaded = datetime.now()

        super().save(*args, **kwargs)

    # get a movie/episode/clip object, depending on the video type
    def get_attached_obj(self):
        if self.type == 'clip':
            return Clip.objects.filter(video =self.pk).first()
        elif self.type == 'movie':
            return Movie.objects.filter(video=self.pk).first()
        elif self.type == 'episode':
            return Episode.objects.filter(video=self.pk).first()

    def get_resource(self):
        obj = self.get_attached_obj()
        if self.type == 'episode':
            return obj.season.show.resource
        return obj.resource
        
    def get_path(self):
        resource = self.get_resource()
        resource_id = resource.pk
        uuid_path = str(self.uuid).replace('-', '')

        return os.path.join(str(resource_id), f"{uuid_path}{self.extension}")
    
    def get_thumbnail_path(self):
        resource = self.get_resource()
        resource_id = resource.pk
        uuid_path = str(self.uuid).replace('-', '')

        return os.path.join(str(resource_id), f"{uuid_path}.webp")
    
    def get_thumbnail_path(self):
        resource = self.get_resource()
        resource_id = resource.pk
        uuid_path = str(self.uuid).replace('-', '')

        return f'{resource_id}/{uuid_path}.webp'
    
    def __str__(self):
        attached_obj = self.get_attached_obj()
        if attached_obj:
            return attached_obj.get_full_name()
        return "Unknown Full Name"

class Movie(models.Model):
    title = models.CharField(max_length=255)
    video = models.OneToOneField(Video, on_delete=models.CASCADE, primary_key=True)
    lead_actor = models.CharField(max_length=255)
    director = models.CharField(max_length=255)
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)

    def get_full_name(self):
        return self.title

class Show(models.Model):
    name = models.CharField(max_length=255)
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)

    def get_image_path(self):
        return f'{self.resource.id}/image.webp'

class Season(models.Model):
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    number = models.PositiveIntegerField()

class Episode(models.Model):
    title = models.CharField(max_length=255)
    season = models.ForeignKey(Season, related_name='episodes', on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    number = models.PositiveIntegerField()
    description = models.TextField(max_length=2048)

    def get_full_name(self):
        return f"{self.season.show.name} - S{self.season.number}E{self.number} - {self.title}"

class Clip(models.Model):
    title = models.CharField(max_length=255)
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

    def get_full_name(self):
        return self.title

class UserVideoTimestamp(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    timestamp = models.PositiveIntegerField()
    last_watched = models.DateTimeField(auto_now=True)

class Subtitle(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    language = models.CharField(max_length=64)
    uuid = models.CharField(max_length=36, default=uuid.uuid4, editable=False, unique=True)

    def get_file_path(self):
        resource = self.video.get_resource()
        path = f"{resource.id}/{self.uuid}.vtt"
        return path

PeakKino/videos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Video, Resource, Clip, Movie, UserVideoTimestamp, Subtitle, Show, Season, Episode
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponseForbidden, JsonResponse, HttpResponseBadRequest
from .forms import ClipUploadForm, MovieUploadForm, ShowCreateForm, SubtitleUploadForm, SeasonCreateForm, EpisodeCreateForm
from accounts.decorators import staff_required, approval_required
from django.urls import reverse
from .utils import delete_folder
from .config import VIDEO_WATCH_UPDATE_INTERVAL
from datetime import datetime
import os
from itertools import chain

@login_required
@approval_required
def watch_video(request, video_id):
    video = get_object_or_404(Video, id=video_id)
    resource = video.get_resource()
    subtitles = Subtitle.objects.filter(video=video)

    user_video_timestamp = UserVideoTimestamp.objects.filter(video=video, user=request.user).first()
    timestamp = 0
    if user_video_timestamp is not None:
        timestamp = user_video_timestamp.timestamp

    if not request.user.can_view_content(resource):
        return HttpResponseForbidden(f"Your age does not permit you to view {resource.age_rating}+ content")

    subs = []
    for subtitle in subtitles:
        subs.append((subtitle.language, '/media/' + subtitle.get_file_path()))

    context = {
        'title' : video.get_attached_obj().title,
        'path' : settings.MEDIA_URL + video.get_path(),
        'updateInterval': VIDEO_WATCH_UPDATE_INTERVAL,
        'id': video.id,
        'timestamp': timestamp,
        'subtitles': subs,
    }
    return render(request, 'watch_video.html', context)

@login_required
@staff_required
@approval_required
def upload_clip(request):
    if request.method == 'POST':
        form = ClipUploadForm(request.POST, request.FILES)
        if form.is_valid():
            clip = form.save(commit=True)
            uploaded_file = request.FILES['upload']
            return redirect('/')  
    else:
        form = ClipUploadForm()
    return render(request, 'upload.html', {'form': form, 'type': 'Clip'})

@login_required
@approval_required
def video_details(request, video_id):
    video = get_object_or_404(Video, id=video_id)
    resource = video.get_resource()
    subtitles = Subtitle.objects.filter(video=video)

    if not request.user.can_view_content(resource):
        return HttpResponseForbidden(f"Your age does not permit you to view {resource.age_rating}+ content")
    
    # get a movie/episode/clip object, depending on the video type
    attached_obj = video.get_attached_obj()
    thumbnail_path = settings.MEDIA_URL + video.get_thumbnail_path()
    video_path = reverse('videos:watch_video', kwargs={'video_id': video_id})


    context = {
        'video': video,
        'resource': resource,
        'attached_obj': attached_obj,
        'thumbnail_path': thumbnail_path,
        'video_path': video_path,
        'subtitles': subtitles,
    }

    return render(request, 'video_details.html', context)

@login_required
@approval_required
def all_videos(request):
    videos = Video.objects.all()

    filtered_videos = []
    for video in videos:
        if request.user.can_view_content(video.get_resource()):
            attached_obj = video.get_attached_obj()
            thumbnail_path = settings.MEDIA_URL + video.get_thumbnail_path()
            details_page_url = reverse('videos:video_details', kwargs = {'video_id': video.pk})
            filtered_videos.append((video, thumbnail_path, attached_obj, details_page_url))

    query = request.GET.get('query', '')
    if query != '':
        queried_videos = []
        
        for video_tuple in filtered_videos:
            video = video_tuple[0]
            if query.lower() in video.get_attached_obj().title.lower():
                queried_videos.append(video_tuple)
    
        filtered_videos = queried_videos
    else:
        query = 'Search for videos...'

    context = {
        'videos': filtered_videos,
        'query': query,
        'type': 'all'
    }
    
    return render(request, 'all_videos.html', context)

@login_required
@approval_required
def content_18_plus(request):
    if request.user.age < 18:
        return HttpResponseForbidden(f"Your age does not permit you to view 18+ content")
    
    filtered_videos = []
    videos = Video.objects.all()
    for video in videos:
        if video.get_resource().age_rating == '18':
            attached_obj = video.get_attached_obj()
            thumbnail_path = settings.MEDIA_URL + video.get_thumbnail_path()
            details_page_url = reverse('videos:video_details', kwargs = {'video_id': video.pk})
            filtered_videos.append((video, thumbnail_path, attached_obj, details_page_url))
    
    query = request.GET.get('query', '')
    if query != '':
        queried_videos = []
        
        for video_tuple in filtered_videos:
            video = video_tuple[0]
            if query.lower() in video.get_attached_obj().title.lower():
                queried_videos.append(video_tuple)
    
        filtered_videos = queried_videos
    else:
        query = 'Search for videos...'

    context = {
        'videos': filtered_videos,
        'query': query,
        'type': 'all',
    }
    
    return render(request, '18_plus.html', context)

@staff_required
@login_required
@approval_required
@require_POST
def delete_clip(request, clip_id):
    clip = get_object_or_404(Clip, pk=clip_id)
    video = clip.video
    resource = video.get_resource()
    path = f"{settings.MEDIA_ROOT}/{resource.pk}"
    user_video_timestamps = UserVideoTimestamp.objects.filter(video=video)
    subtitles = Subtitle.objects.filter(video=video)
    for subtitle in subtitles:
        delete_subtitle(request, subtitle.id)

    for timestamp in user_video_timestamps:
        timestamp.delete()
    delete_folder(path)
    clip.delete()
    video.delete()
    resource.delete()

    return JsonResponse({'success': True, 'message': 'Clip deleted succesfully'})

@login_required
@staff_required
@approval_required
def upload_movie(request):
    if request.method == 'POST':
        form = MovieUploadForm(request.POST, request.FILES)
        if form.is_valid():
            movie = form.save(commit=True)
            uploaded_file = request.FILES['upload']
            return redirect('/')  
    else:
        form = MovieUploadForm()
    return render(request, 'upload.html', {'form': form, 'type': 'Movie'})

@staff_required
@login_required
@approval_required
@require_POST
def delete_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    video = movie.video
    resource = video.get_resource()
    path = f"{settings.MEDIA_ROOT}/{resource.pk}"
    user_video_timestamps = UserVideoTimestamp.objects.filter(video=video)
    subtitles = Subtitle.objects.filter(video=video)
    for subtitle in subtitles:
        delete_subtitle(request, subtitle.id)

    for timestamp in user_video_timestamps:
        timestamp.delete()
    delete_folder(path)
    movie.delete()
    video.delete()
    resource.delete()

    return JsonResponse({'success': True, 'message': 'Movie deleted succesfully'})

@login_required
@approval_required
def all_movies(request):
    movies = Movie.objects.all()

    filtered_movies = []
    for movie in movies:
        if request.user.can_view_content(movie.resource):
            video = movie.video
            thumbnail_path = settings.MEDIA_URL + video.get_thumbnail_path()
            details_page_url = reverse('videos:video_details', kwargs = {'video_id': video.pk})
            filtered_movies.append((video, thumbnail_path, movie, details_page_url))
   
    query = request.GET.get('query', '')
    if query != '':
        queried_movies = []
        
        for movie_tuple in filtered_movies:
            movie = movie_tuple[2]
            if query.lower() in movie.title.lower():
                queried_movies.append(movie_tuple)
    
        filtered_movies = queried_movies
    else:
        query = 'Search for movies...'

    context = {
        'videos': filtered_movies,
        'query': query,
        'type': 'movies',
        'upload_url': reverse('videos:upload_movie'),
    }
    
    return render(request, 'all_videos.html', context)

@login_required
@approval_required
def all_clips(request):
    clips = Clip.objects.all()

    filtered_clips = []
    for clip in clips:
        if request.user.can_view_content(clip.resource):
            video = clip.video
            thumbnail_path = settings.MEDIA_URL + video.get_thumbnail_path()
            details_page_url = reverse('videos:video_details', kwargs= {'video_id': video.pk})
            filtered_clips.append((video, thumbnail_path, clip, details_page_url))
    
    query = request.GET.get('query', '')
    if query != '':
        queried_clips = []
        
        for clip_tuple in filtered_clips:
            clip = clip_tuple[2]
            if query.lower() in clip.title.lower():
                queried_clips.append(clip_tuple)
    
        filtered_clips = queried_clips
    else:
        query = 'Search for clips...'

    context = {
        'videos': filtered_clips,
        'query': query,
        'type': 'clips',
        'upload_url': reverse('videos:upload_clip'),
    }
    
    return render(request, 'all_videos.html', context)

@login_required
@staff_required
@approval_required
def create_show(request):
    if request.method == 'POST':
        form = ShowCreateForm(request.POST, request.FILES)
        if form.is_valid():
            show = form.save(commit=True)
            return redirect('/')
    else:
        form = ShowCreateForm()
    return render(request, 'upload_show.html', {'form': form})

@login_required
@approval_required
def search(request):
    query = request.GET.get('query', '')
    type = request.GET.get('type', '')

PeakKino/videos/templates/18_plus.html
{% extends 'base.html' %}

{% block content %}
    {% for video, thumbnail_path, attached_obj, details_page_url in videos %}
        <h2>{{ attached_obj.title }}</h2>
        <img src="{{ thumbnail_path }}" style="max-width: 50%; max-height: 300px"/>
        <br/>
        {% if video.type == 'movie' %}
            <p>Type: movie</p>
            <p>Director: {{ attached_obj.director }}</p>
            <p>Lead actor: {{ attached_obj.lead_actor }}</p>
        {% endif %}
        <a href="{{ details_page_url }}">WATCH</a>
    {% endfor %}
{% endblock %}

{% block extra_scripts %}
{% endblock %}

PeakKino/videos/templates/all_shows.html
{% extends 'all_stuff_base.html' %}
{% block extra_content %}
    {% if request.user.is_staff %}
        <div class="clickable-div" data-url="{{upload_url}}">
            <div class="upload-container">
                <div class="upload-image-container">
                </div>
                <h3>Upload shows</h3>
            </div>
        </div>
    {% endif %}
    <div class="shows">
        {% for show in shows %}
            <div class="clickable-div" data-url="{% url 'videos:show_details' show.id %}">
                <div class="show-content-container">
                    <div class="show-container">
                        <img src="/media/{{ show.get_image_path }}"/>
                        <div class="show-info">
                            <h2>{{show.name}}</h2>
                        </div>
                    </div>
                    {% if request.user.is_staff %}
                        <button class="delete-button" id="{{show.id}}">Delete</button>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

PeakKino/videos/templates/all_stuff_base.html
{% extends 'base.html' %}
{% block content %}
    <div class="alternate-search-container">
        <input type="text" id="alternate-search-input" placeholder="{{query}}"/>
        <form id="alternate-search-form">
            <select id="alternate-type-select" name="type">
                <option value="all" selected>All</option>
                <option value="movies">Movies</option>
                <option value="clips">Clips</option>
                <option value="shows">Shows</option>
            </select>
        </form>
        <button id="alternate-search-button">Search</button>
    </div>
    {% block extra_content %}
    {% endblock %}
{% endblock %}

{% block extra_scripts %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var defaultType = "{{type}}";

            var typeSelect = document.getElementById('type-select');
            typeSelect.value = defaultType;

            document.getElementById('search-button').addEventListener('click', function() {
                var query = document.getElementById('search-input').value;
                var type = typeSelect.value;
                var url = '/videos/search/?query=' + encodeURIComponent(query) + '&type=' + type;
                console.log(url);
                window.location.href = url;
            });

            var typeSelect = document.getElementById('alternate-type-select');
            typeSelect.value = defaultType;

            document.getElementById('alternate-search-button').addEventListener('click', function() {
                var query = document.getElementById('alternate-search-input').value;
                var type = typeSelect.value;
                var url = '/videos/search/?query=' + encodeURIComponent(query) + '&type=' + type;
                console.log(url);
                window.location.href = url;
            });
        });
    </script>
    <script>
        document.addEventListener("click", function(event) {
            if (event.target.classList.contains("delete-button")) {
                const id = event.target.id;
                const type = '{{ type }}'.slice(0, -1);
                deleteItem(id, type);
            }
        });
    
        function deleteItem(id, type) {
            fetch(`/videos/delete/${type}/${id}/`, {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                },
            })
            .then(response => {
                if (response.ok) {
                    location.reload();
                } else {
                    console.error('Failed to delete item');
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        }
    </script>
{% endblock %}

PeakKino/videos/templates/all_videos.html
{% extends 'all_stuff_base.html' %}
{% block extra_content %}
    {% if type != 'all' and request.user.is_staff %}
        <div class="clickable-div" data-url="{{upload_url}}">
            <div class="upload-container">
                <div class="upload-image-container">

                </div>
                <h3>Upload {{type}}</h3>
            </div>
        </div>
    {% endif %}
    {% for video, thumbnail_path, attached_obj, details_page_url in videos %}
            <h2>{{ attached_obj.title }}</h2>
            <img src="{{ thumbnail_path }}" style="max-width: 50%; max-height: 300px"/>
            <br/>
            {% if video.type == 'movie' %}
                <p>Type: movie</p>
                <p>Director: {{ attached_obj.director }}</p>
                <p>Lead actor: {{ attached_obj.lead_actor }}</p>
            {% endif %}
            <a href="{{ details_page_url }}">WATCH</a>
            {% if request.user.is_staff %}
                <a href="{% url 'videos:upload_subtitle' video.id  %}">Add subtitle</a>
            {% endif %}
            {% if type != 'all' %}
                <button class="delete-button" id="{{attached_obj.pk}}">Delete</button>
            {% endif %}
    {% endfor %}
{% endblock %}

PeakKino/videos/templates/show_details.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{show.name}}</h1>
    <img src="/media/{{show.get_image_path}}">
    {% if request.user.is_staff %}
        <a href="{% url 'videos:create_season' show.id %}">Add season</a>
    {% endif %}
    <div class="seasons">
        {% for season in seasons %}
        <div class="episodes">
            <h2>{{season.number}}: {{season.name}}</h2>
            {% for episode in episodes %}
                {% if episode.season == season %}
                    <h3>{{episode.title}}</h3>
                    <a href="{% url 'videos:video_details' episode.video.id %}">Watch</a>
                    <p>{{episode.description}}</p>
                    {% if request.user.is_staff %}
                        <button class="delete-button" id="{{ episode.id }}">Delete episode</button>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
        {% if request.user.is_staff %}
            <a href="{% url 'videos:upload_episode' season.id %}">Upload an episode</a>
            <button class="delete-button-season" id="{{ season.id }}">Delete season</button>
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}

{% block extra_scripts %}
<script>
        document.addEventListener("click", function(event) {
            if (event.target.classList.contains("delete-button")) {
                const id = event.target.id;
                deleteItem(id);
            }
        });
        
        function deleteItem(id) {
            fetch(`/videos/delete/episode/${id}/`, {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                },
            })
            .then(response => {
                if (response.ok) {
                    location.reload();
                } else {
                    console.error('Failed to delete item');
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        }
    </script>
    <script>
        document.addEventListener("click", function(event) {
            if (event.target.classList.contains("delete-button-season")) {
                const id = event.target.id;
                deleteSeason(id);
            }
        });
        
        function deleteSeason(id) {
            fetch(`/videos/delete/season/${id}/`, {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                },
            })
            .then(response => {
                if (response.ok) {
                    location.reload();
                } else {
                    console.error('Failed to delete item');
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        }
    </script>
{% endblock %}

PeakKino/videos/templates/upload.html
{% extends 'base.html' %}
{% block content %}
<h1 id="upload-title">Upload {{ type }}</h1>
    <div class="form-wrapper">
        <form method="post" enctype="multipart/form-data" class="upload-form">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <button id="submit-button" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

PeakKino/videos/templates/upload_clip.html
{% extends 'base.html' %}
{% block content %}
<h1>Upload Clip</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

PeakKino/videos/templates/upload_episode.html
{% extends 'base.html' %}
{% block content %}
<h1 id="upload-title">Upload episode for:</h1>
<div class="form-wrapper">
    <h2 id="show-name">{{show.name}}</h2>
    <h3 id="season-name">{{season.number}}. {{season.name}}</h3>
    <img src="{{image_url}}">
    <form method="post" enctype="multipart/form-data" class="upload-form">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <button type="submit" id="submit-button">Submit</button>
    </form>
    <button id="autohelp-button">Auto fill info</button>
</div>
<div class="results">
        
</div>
{% endblock %}

{% load static %}
{% block extra_scripts %}
    <script src="{% static 'episode_autofill.js' %}"></script>
{% endblock %}

PeakKino/videos/templates/upload_show.html
{% extends 'base.html' %}
{% block content %}
<h1>Upload show</h1>
    <div class="form-wrapper">
        <form method="post" enctype="multipart/form-data" class="upload-form">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <button type="submit">Submit</button>
        </form>
        <button id="autohelp-button">Auto fill info</button>
    </div>
    <div class="results">
        
    </div>
{% endblock %}

{% load static %}
{% block extra_scripts %}
    <script src="{% static 'show_autofill.js' %}"></script>
{% endblock %}

PeakKino/videos/templates/video_details.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ attached_obj.get_full_name }}</h1>
<img src="{{ thumbnail_path }}" style="max-width: 100%; max-height: 75vh;"/>
<h3><a href="{{ video_path }}">WATCH NOW</a></h3>
{% if request.user.is_staff %}
    <a href="{% url 'videos:upload_subtitle' video.id  %}">Add subtitle</a>
{% endif %}
<h2>Avalible subtitles: </h2>
{% for subtitle in subtitles %}
    <div>
        <p>{{subtitle.language}}</p>
        {% if user.is_staff %}
            <button class="delete-button" id="{{subtitle.id}}">Delete</button>
        {% endif %}
    </div>
{% endfor %}
{% endblock %}

{% if user.is_staff %}
    {% block extra_scripts %}
        <script>
            document.addEventListener("click", function(event) {
                if (event.target.classList.contains("delete-button")) {
                    const id = event.target.id;
                    deleteItem(id);
                }
            });
        
            function deleteItem(id) {
                fetch(`/videos/delete/subtitle/${id}/`, {
                    method: 'POST',
                    credentials: 'same-origin',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                })
                .then(response => {
                    if (response.ok) {
                        location.reload();
                    } else {
                        console.error('Failed to delete item');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                });
            }
        </script>
    {% endblock %}
{% endif %}